### ISSUE TITLE
When token expiration is detected, logout user

### ISSUE THREAD

**Issue by randomouscrap98** [12Me21/sbs2#32] opened 2022-07-20 05:51 UTC
Current, when a token is detected to be expired, you just get a broken user tab that you still have to manually log out of. I think it would be a better user experience if either a logout occurred or at least the UI was updated so you can log in again without going to the broken user tab. A reload doesn't fix it, it's just always a "bad token" alert with the broken user tab until you specifically press the logout button.

**Comment by randomouscrap98** [comment] 2022-07-20 05:52
![image](https://user-images.githubusercontent.com/13357277/179906805-c44baa6f-cd51-4558-860d-648d835603c1.png)
Just to show what happens.

**Comment by 12Me21** [comment] 2022-07-21 14:12
oh yeah i just wasn't confident that i was detecting the invalid token reliably
(since i think the same error would happen if, like: i forgot to pass the token to the websocket)
so i didn't want to automatically log out the user, in case this was caused by a bug rather than an actual expired token

**Comment by 12Me21** [comment] 2022-07-21 14:15
fixed by 257f6f035017774c104bc1dcc4220191606c3539 (probably, don't feel like checking lol)

**Closed as completed by 12Me21** 2022-07-21 14:15 UTC
